sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - nightly # PHP 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction -vvv


before_script:


script: